/* ===========================================================================
   Balsalameh platform — Microsoft SQL Server schema
   ---------------------------------------------------------------------------
   Run this in SSMS against an EMPTY database, OR apply the same shape with:
       npx prisma db push
   The column / table names match prisma/schema.prisma exactly, so either
   method produces a database the app can use.

   Identifiers (Ids) are 30-char strings generated by the application
   (Prisma `cuid()`), so there are no IDENTITY columns.
   =========================================================================== */

SET XACT_ABORT ON;
BEGIN TRANSACTION;

/* ---------- AdminUsers ---------------------------------------------------- */
CREATE TABLE dbo.AdminUsers (
    id            NVARCHAR(30)  NOT NULL CONSTRAINT PK_AdminUsers PRIMARY KEY,
    username      NVARCHAR(50)  NOT NULL,
    email         NVARCHAR(256) NOT NULL,
    name          NVARCHAR(120) NOT NULL,
    passwordHash  NVARCHAR(256) NOT NULL,
    passwordSalt  NVARCHAR(64)  NOT NULL,
    lastLoginAt   DATETIME2     NULL,
    createdAt     DATETIME2     NOT NULL CONSTRAINT DF_AdminUsers_createdAt DEFAULT SYSUTCDATETIME(),
    updatedAt     DATETIME2     NOT NULL CONSTRAINT DF_AdminUsers_updatedAt DEFAULT SYSUTCDATETIME()
);
CREATE UNIQUE INDEX UX_AdminUsers_username ON dbo.AdminUsers(username);
CREATE UNIQUE INDEX UX_AdminUsers_email    ON dbo.AdminUsers(email);

/* ---------- Transactions ----------------------------------------------------
   Created first so Members can FK to it. */
CREATE TABLE dbo.Transactions (
    id                     NVARCHAR(30)  NOT NULL CONSTRAINT PK_Transactions PRIMARY KEY,
    reference              NVARCHAR(40)  NOT NULL,
    provider               NVARCHAR(20)  NOT NULL CONSTRAINT DF_Transactions_provider DEFAULT 'MEPS',
    providerRef            NVARCHAR(100) NULL,
    amountMinor            INT           NOT NULL,
    currency               NVARCHAR(3)   NOT NULL CONSTRAINT DF_Transactions_currency DEFAULT 'JOD',
    status                 NVARCHAR(20)  NOT NULL CONSTRAINT DF_Transactions_status DEFAULT 'PENDING',
    fullName               NVARCHAR(120) NOT NULL,
    email                  NVARCHAR(256) NOT NULL,
    consentTermsAccepted   BIT           NOT NULL CONSTRAINT DF_Transactions_consentTerms DEFAULT 0,
    consentPrivacyAccepted BIT           NOT NULL CONSTRAINT DF_Transactions_consentPriv  DEFAULT 0,
    consentVersion         NVARCHAR(20)  NULL,
    failureReason          NVARCHAR(400) NULL,
    rawResponse            NVARCHAR(MAX) NULL,
    ipnReceivedAt          DATETIME2     NULL,
    createdAt              DATETIME2     NOT NULL CONSTRAINT DF_Transactions_createdAt DEFAULT SYSUTCDATETIME(),
    updatedAt              DATETIME2     NOT NULL CONSTRAINT DF_Transactions_updatedAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT CK_Transactions_status CHECK (status IN ('PENDING','CAPTURED','FAILED','REFUNDED'))
);
CREATE UNIQUE INDEX UX_Transactions_reference ON dbo.Transactions(reference);
CREATE INDEX IX_Transactions_status    ON dbo.Transactions(status);
CREATE INDEX IX_Transactions_createdAt ON dbo.Transactions(createdAt);

/* ---------- Members ---------------------------------------------------------
   Spec: store only full name, email, Membership ID, expiry month + year.
   status/purchasedAt/transactionId are operational. */
CREATE TABLE dbo.Members (
    id            NVARCHAR(30)  NOT NULL CONSTRAINT PK_Members PRIMARY KEY,
    membershipId  NVARCHAR(20)  NOT NULL,
    fullName      NVARCHAR(120) NOT NULL,
    email         NVARCHAR(256) NOT NULL,
    expiryMonth   INT           NOT NULL,
    expiryYear    INT           NOT NULL,
    status        NVARCHAR(20)  NOT NULL CONSTRAINT DF_Members_status DEFAULT 'ACTIVE',
    purchasedAt   DATETIME2     NOT NULL,
    transactionId NVARCHAR(30)  NULL,
    createdAt     DATETIME2     NOT NULL CONSTRAINT DF_Members_createdAt DEFAULT SYSUTCDATETIME(),
    updatedAt     DATETIME2     NOT NULL CONSTRAINT DF_Members_updatedAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT CK_Members_status       CHECK (status IN ('ACTIVE','EXPIRED','REVOKED')),
    CONSTRAINT CK_Members_expiryMonth  CHECK (expiryMonth BETWEEN 1 AND 12),
    CONSTRAINT FK_Members_transaction  FOREIGN KEY (transactionId) REFERENCES dbo.Transactions(id)
);
CREATE UNIQUE INDEX UX_Members_membershipId  ON dbo.Members(membershipId);
CREATE UNIQUE INDEX UX_Members_transactionId ON dbo.Members(transactionId) WHERE transactionId IS NOT NULL;
CREATE INDEX IX_Members_email  ON dbo.Members(email);
CREATE INDEX IX_Members_status ON dbo.Members(status);

/* ---------- WebhookEvents (MEPS IPN dedupe) ---------------------------------- */
CREATE TABLE dbo.WebhookEvents (
    id             NVARCHAR(30)  NOT NULL CONSTRAINT PK_WebhookEvents PRIMARY KEY,
    provider       NVARCHAR(20)  NOT NULL CONSTRAINT DF_WebhookEvents_provider DEFAULT 'MEPS',
    dedupeKey      NVARCHAR(200) NOT NULL,
    signatureValid BIT           NOT NULL CONSTRAINT DF_WebhookEvents_sig DEFAULT 0,
    payload        NVARCHAR(MAX) NOT NULL,
    result         NVARCHAR(20)  NULL,
    error          NVARCHAR(400) NULL,
    processedAt    DATETIME2     NULL,
    createdAt      DATETIME2     NOT NULL CONSTRAINT DF_WebhookEvents_createdAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT CK_WebhookEvents_result CHECK (result IS NULL OR result IN ('ok','ignored','error'))
);
CREATE UNIQUE INDEX UX_WebhookEvents_dedupeKey ON dbo.WebhookEvents(dedupeKey);
CREATE INDEX IX_WebhookEvents_createdAt ON dbo.WebhookEvents(createdAt);

/* ---------- EmailLogs ------------------------------------------------------ */
CREATE TABLE dbo.EmailLogs (
    id                NVARCHAR(30)  NOT NULL CONSTRAINT PK_EmailLogs PRIMARY KEY,
    type              NVARCHAR(40)  NOT NULL,
    toAddress         NVARCHAR(256) NOT NULL,
    subject           NVARCHAR(200) NOT NULL,
    status            NVARCHAR(20)  NOT NULL CONSTRAINT DF_EmailLogs_status DEFAULT 'queued',
    providerMessageId NVARCHAR(120) NULL,
    error             NVARCHAR(400) NULL,
    memberId          NVARCHAR(30)  NULL,
    createdAt         DATETIME2     NOT NULL CONSTRAINT DF_EmailLogs_createdAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT CK_EmailLogs_status CHECK (status IN ('queued','sent','delivered','bounced','failed')),
    CONSTRAINT FK_EmailLogs_member FOREIGN KEY (memberId) REFERENCES dbo.Members(id)
);
CREATE INDEX IX_EmailLogs_status ON dbo.EmailLogs(status);

/* ---------- AuditLogs ---------------------------------------------------- */
CREATE TABLE dbo.AuditLogs (
    id        NVARCHAR(30)  NOT NULL CONSTRAINT PK_AuditLogs PRIMARY KEY,
    action    NVARCHAR(60)  NOT NULL,
    entity    NVARCHAR(40)  NOT NULL,
    entityId  NVARCHAR(60)  NOT NULL,
    detail    NVARCHAR(MAX) NULL,
    actorId   NVARCHAR(30)  NULL,
    createdAt DATETIME2     NOT NULL CONSTRAINT DF_AuditLogs_createdAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_AuditLogs_actor FOREIGN KEY (actorId) REFERENCES dbo.AdminUsers(id)
);
CREATE INDEX IX_AuditLogs_entity   ON dbo.AuditLogs(entity, entityId);
CREATE INDEX IX_AuditLogs_createdAt ON dbo.AuditLogs(createdAt);

COMMIT TRANSACTION;
GO

/* ===========================================================================
   First admin account.
   The password is stored as scrypt(salt, password). Generate real values with:
       npm run db:seed        (reads ADMIN_USERNAME / ADMIN_PASSWORD / ... from .env)
   or run this stub now and change the password from Admin > My profile after
   seeding. The line below is a PLACEHOLDER hash for username "admin" /
   password "admin1234" and MUST be rotated before launch.
   =========================================================================== */
-- INSERT INTO dbo.AdminUsers (id, username, email, name, passwordHash, passwordSalt)
-- VALUES ('seed_admin_0000000000000000000', 'admin', 'admin@example.com', 'Administrator',
--         '<scrypt-hash-hex>', '<salt-hex>');
